# where am I
#cluster.name: wally
network.host: 0.0.0.0

# who am I
#node.name: mewtwo

# birl
node.master: true
node.data: true
action.destructive_requires_name: true

# free-tier
xpack.security.enabled: false
xpack.monitoring.enabled: true
xpack.graph.enabled: false
xpack.watcher.enabled: false
